name: Go CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21' # Or your preferred Go version

      - name: Build
        run: go build -v ./...

      - name: Run
        run: go run main.go
      
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: |
            test.txt
          retention-days: 7
        
